---
- name: "Copy the zip file to EC2 instance"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Create backend app directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "unarchive directory"
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/backend
    copy: no

- name: "Install Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: "Start the backend app"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- start
    pm2 ls

    